apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      namespace: default
  template:
    metadata:
      labels:
        app: nginx
        namespace: default
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          namespace: default
          ports:
            - containerPort: 80
